name: Preview Release

on:
  push:
  pull_request:

permissions: {}

jobs:
  preview:
    name: Preview Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Use pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm build

      - name: Publish Preview
        run: pnpm dlx pkg-pr-new publish --compact --pnpm './packages/*' './exchanges/*'
